### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in "" This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

### ISSUE THREAD

**Issue by Justice996** [LC044/WeChatMsg#65]
**bug描述**
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/27287643/ef1f1801-6be0-4129-9ad5-1a293f30da3d)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win1]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**

**Comment by Fusuccess** [comment]
`D:\project\WeChatMsg-master>python main_pc.py
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

**运行环境：**
-  Python版本： 3.12.0
-  微信版本：3.9.7.29

**Comment by LC044** [comment]
重装pyqt是否能解决该问题
